dharanews/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('newsapp.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

newsapp/urls.py
from django.urls import path
from .import views


urlpatterns = [
        path('',views.index,name="index"),
        path('blog/category/<int:id>',views.blog,name="blog"),
        path('blog_details/<str:slug>',views.blog_details,name="blog_details"),
        path('userpost_details/<str:slug>',views.userpost_details,name="userpost_details"),
        path('userlogin',views.userlogin,name="userlogin" ),
        path('userlogout',views.userlogout,name="userlogout" ),
        path('usersignup',views.usersignup,name="usersignup" ),
        path('add_post',views.add_post,name="add_post" ),
        path('add_post2',views.add_post2,name="add_post2" ),
        path('post_list',views.post_list,name="post_list" ),
        path('edit_post2/<int:id>',views.edit_post2,name="edit_post2" ),
        path('delete_post/<int:id>',views.delete_post,name='delete_post'),
        # footer
        path('disclaimer',views.disclaimer,name="disclaimer" ),
        path('privacy_policy',views.privacy_policy,name="privacy_policy" ),
        path('terms_condition',views.terms_condition,name="terms_condition" ),
        path('fraud_alert',views.fraud_alert,name="fraud_alert" ),
        path('faq',views.faq,name="faq"),
        




]

newsapp/models.py
from django.db import models
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.

class StudentUser(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    type=models.CharField(max_length=15)
    def __str__(self):
        return self.user.username

class Category(models.Model):
    name=models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Sub_Category(models.Model):
    name=models.CharField(max_length=50)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    def __str__(self):
        return self.name


class Post(models.Model):
    author=models.ForeignKey(StudentUser,on_delete=models.CASCADE)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    sub_category=models.ForeignKey(Sub_Category,on_delete=models.CASCADE)
    title=models.CharField(max_length=200)
    slug=AutoSlugField(populate_from='title',unique=True,null=True,default=None)
    image=models.FileField()
    desc=RichTextField()
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Footer(models.Model):
    terms_condition=RichTextField(null=True,blank=True)
    fraud_alert=RichTextField(null=True,blank=True)
    disclaimer=RichTextField(null=True,blank=True)
    privacy_policy=RichTextField(null=True,blank=True)
    faq=RichTextField(null=True,blank=True)
    

templates/add_post.html
{% extends 'base.html' %}
{%load static%}

{% block body %}  

{%for msg in messages%}
<div class="alert alert-{{msg.tags}} alert-dismissible fade show" role="alert">
  <strong>Message : </strong> {{msg}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{%endfor%}
  <!-- ======= Contact Section ======= -->


  <section id="contact" class="contact">
    <div class="container">

      <div class="row mt-5">

        <div class="col-lg-11 mt-5 mt-lg-0" data-aos="fade-left">

          <form action="{% url 'add_post' %}" method="post" enctype="multipart/form-data" role="form" >{% csrf_token %}
            <div class="row">
              <div class="form-group mt-3">
                <label for="">Category : </label>
                <div class="col-sm-12">
								  <select  class="form-control" id="colFormLabel"  name="category" id="cars">
									  {% for i in category%}
									  <option value="{{i.name}}">{{i.name}}</option>
									  {%endfor%}
									</select>
								</div>
                
              </div>
              <div class="form-group mt-3">
              <div class="col-sm-12 ">
                <label for="">Sub Category : </label>
                <select  class="form-control" id="colFormLabel"  name="sub_category" id="cars">
                  {% for i in sub_category%}
                  <option value="{{i.name}}">{{i.name}}</option>
                  {%endfor%}
                </select>
              </div>
            </div>
            <div class="form-group mt-3">
              <input type="text" class="form-control" name="title" id="subject" placeholder="Title">
            </div>
            <div class="form-group mt-3">
              <input type="text" class="form-control" name="blogger" value="{{request.user}}" readonly id="email" placeholder="Your Email ID">
            </div>
            <div class="form-group mt-3">
              <input type="file" class="form-control" name="image"  id="email"  required>
            </div>
            <div class="form-group mt-3">
              
              <textarea class="form-control" name="desc"   rows="5" placeholder="Description" required></textarea>
              
            </div>
            <!-- <div class="my-3">
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your message has been sent. Thank you!</div>
            </div> -->
            
            <div class="text-center my-3"><button type="submit" class="btn btn-success">Add Post</button></div>
          </form>

        </div>

      </div>

    </div>
  </section><!-- End Contact Section -->

 {% endblock %}

templates/add_post2.html
{% extends 'postbase.html' %}
{%load static%}

{% block body %}  

{%for msg in messages%}
<div class="alert alert-{{msg.tags}} alert-dismissible fade show" role="alert">
  <strong>Message : </strong> {{msg}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{%endfor%}
  <!-- ======= Contact Section ======= -->


  <section id="contact" class="contact">
    <div class="container">

      <div class="row mt-5">

        <div class="col-lg-11 mt-5 mt-lg-0" data-aos="fade-left">

          <form  method="post" enctype="multipart/form-data" >{% csrf_token %}
            <div class="row">
                {{form.as_p}}
           
                {{form.media}}
            <div class="text-center my-3"><button type="submit" class="btn btn-success">Add Post</button></div>
          </form>

        </div>

      </div>

    </div>
  </section><!-- End Contact Section -->

 {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Lowkot</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
<!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
<!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
<!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Remember - v4.6.0
  * Template URL: https://bootstrapmade.com/remember-free-multipurpose-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope d-flex align-items-center"><a >dharanews@gmail.com</a></i>
        <i class="bi bi-phone d-flex align-items-center ms-4"><span>+91-9015707816</span></i>
      </div>
      <div class="social-links d-none d-md-flex align-items-center">
        <a href="https://twitter.com/" target="_blank" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="https://www.facebook.com/" target="_blank" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="https://www.instagram.com/" target="_blank" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="https://www.linkedin.com/" target="_blank" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
      </div>
    </div>
  </section>

  <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex justify-content-between">

      <div class="logo">
        <h1 class="text-light"><a href="/">DharaNews</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.jpg" alt="" class="img-fluid">Lowkot</a> -->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="/">Blogs</a></li>
          {% for cat in category %}
          <li class="nav-item dropdown">
            
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             {{cat.name}}
            </a>
            
            
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in cat.sub_category_set.all %}
              <li><a class="dropdown-item" href="/blog/category/{{i.id}}">{{i.name}}</a></li>
              {% endfor %}
              
            </ul>
            
            
          </li>
          {% endfor %}
          <!-- <li><a class="nav-link scrollto" href="{% url 'add_post' %}">Add Post</a></li> -->
          <li><a class="nav-link scrollto" href="{% url 'userlogin' %}">Login</a></li>
          <!-- <li><a class="nav-link scrollto" href="{% url 'userlogout' %}">Logout</a></li> -->
            
        </ul>
        
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
    </div>
  </header><!-- End Header -->

{%block body%} {% endblock %}

<!-- ======= Footer ======= -->
<footer id="footer">

    <div class="container footer-bottom clearfix">

      <div class="text-center">
        
        <a href="/faq">FAQs</a> | 
        
        
        <a href="/privacy_policy">Privacy Policy</a> | 
        
        <a href="/fraud_alert">Fraud Alert</a> | 
        <a href="/terms_condition">Terms &amp; Conditions</a> | 
        <a href="/disclaimer">Disclaimer</a>
       </div>

       <div class="row align-items-center">
        <div class="divider-20 d-none d-lg-block"></div>

        
        <div class="col-md-12 text-center"><p>&copy; Copyright 2022</span> All Rights Reserved</p></div>
        <div class="divider-20 d-none d-lg-block"></div>
    </div>
      <!-- <div class="copyright">
        &copy; Copyright <strong><span>Remember</span></strong>. All Rights Reserved
      </div> -->
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/remember-free-multipurpose-bootstrap-template/ -->
        Designed by <a href="https://lowkot.com/">Lowkot</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/aos/aos.js' %} "></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %} "></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %} "></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %} "></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter.js' %} "></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %} "></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/blog.html
{% extends 'base.html' %}
{%load static%}
{% block body %}  

	
    <!-- ======= Why Us Section ======= -->
    <section id="why-us" class="why-us">
      <div class="container">

        
        <div class="row">
          {% for i in post %}
          <div class="col-lg-4">
            <div class="box"  data-aos="fade-up " >
              <a href="/blog_details/{{i.slug}}"><img src="{{i.image.url}}" style="height:200px;width:300px;" alt=""></a>
              <a href="/blog_details/{{i.slug}}"><h4>{{i.title}}</h4></a>
              <p>{{i.desc | slice:"0:200" | safe}} </p>
             
              <p class="my-3">{{i.date}}</p>
            </div>
          </div>
          {% endfor %}

        </div>
        <br><br>
     
      </div>

    
    </section><!-- End Why Us Section -->

  
   
  
  </main><!-- End #main -->

   {% endblock %}

templates/blog_details.html
{% extends 'base.html' %}
{%load static%}
{% block body %}  
    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row gy-4">
          {% for i in post%}
          <div class="col-lg-8">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">
               
                <div   >
                  <img src="{{i.image.url}}"   style="height: 400px; width: 700px;" alt="">
                </div>

              </div>
             
            </div>
          </div>
          {%endfor%}

          <div class="col-lg-4 ">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">
                
               
                <div   >
                  
                  <img src="{% static 'assets/img/testimonials-bg.jpg' %}"   style="height: 400px; width: 350px;" alt="">
                </div>

              </div>
             
            </div>
          </div>
          
          {% for i in post%}
          <div class="col-lg-12">
           
            <div class="portfolio-description">
              <h2>{{i.title}}</h2>
              <p>
               {{i.desc|safe}}
              </p>
            </div>
          </div>
          {%endfor%}
        </div>

      </div>
    </section><!-- End Portfolio Details Section -->

  </main><!-- End #main -->

   {%endblock%}

templates/edit_post2.html
{% extends 'postbase.html' %}

{%block body%}

<div class="container mt-4">
    
<div class="row">
    <div class="col-sm-8 offset-2">
        
        <form  method="POST" enctype="multipart/form-data">

            {% csrf_token %}
           
              {{form.as_p}}
           
              {{form.media}}
            
            <br><br>
            <button class="btn btn-success">Update Post</button>
           <!-- <a href="/" class="btn btn-success">Back</a> -->

        </form>
    </div>

</div>
</div>

<div class="container mt-3">
    </div>
{%endblock%}

templates/index.html
{% extends 'base.html' %}
{%load static%}
{% block body %}  
  <!-- ======= Hero Section ======= -->
  <!-- <section id="hero">
    <div class="hero-container" data-aos="fade-up">
      <h1>Comradeship Program ! Become a Leagend</h1>
      <h2>We are offering to be partners with us for the contribute to the world's greatest cause</h2>
      <a href="#about" class="btn-get-started scrollto">Get Started</a>
    </div>
  </section> -->
  <!-- End Hero -->

  <!-- slider -->
  <div class="row">
    <div class="col-lg-6">
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      {% for i in post %}
      <div class="carousel-item {% if forloop.counter0 == 0%} active {%endif%}">
       
        <img src="{{i.image.url}}" height="400px" class="d-block w-100" alt="...">
        </div>

        
     
     {%endfor%}
      
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<div class="col-lg-3">
  <div   >
                  
    <img src="{% static 'assets/img/vertical-8.jpg' %}"   style="height: 400px; width:300px;" alt="">
  </div>
</div>

<div class="col-lg-3">
  <div   >
                  
    <img src="{% static 'assets/img/testimonials-bg.jpg' %}"   style="height: 400px; width:300px;" alt="">
  </div>
</div>

</div>
<!-- end slider -->


  <main id="main">

   <!-- ======= Team Section ======= -->
    <section id="team" class="team">
      <div class="container">

        <div class="section-title" data-aos="zoom-in">
          <h2>Posts</h2>
          <h3>Our Latest Posts </h3>
        </div>

        <div class="row">
          {% for i in post %}
          <div class="col-lg-3 col-md-6 d-flex align-items-stretch" >
            <div class="member" data-aos="fade-up">
              <div class="member-img">
                <a href="/blog_details/{{i.slug}}"><img src="{{i.image.url}}" style="height: 200px;" class="img-fluid" alt=""></a>
                <!-- <div class="social">
                  <a href=""><i class="bi bi-twitter"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div> -->
              </div>
              <div class="member-info">
                <a href="/blog_details/{{i.slug}}"><h4>{{i.title|slice:"0:50"}}</h4></a>
                <p>{{i.desc | slice:"0:100" | safe}}</p>
                <!-- <span>Chief Executive Officer</span> -->
              </div>
            </div>
          </div>
          {%endfor%}

          <!-- <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member" data-aos="fade-up" data-aos-delay="100">
              <div class="member-img">
                <img src="{% static 'assets/img/team/team-2.jpg' %}" class="img-fluid" alt="">
                <div class="social">
                  <a href=""><i class="bi bi-twitter"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>Sarah Jhonson</h4>
                <span>Product Manager</span>
              </div>
            </div>
          </div> -->

           <!-- pagination -->
    
       <nav aria-label="...">
        <ul class="pagination">
        {% if post.has_previous %}	
          <li class="page-item ">
          <a class="page-link" href="/?page=1" tabindex="-1" aria-disabled="true">First</a>
          </li>
          <li class="page-item ">
          <a class="page-link" href="/?page={{post.previous_page_number}}" tabindex="-1" aria-disabled="true">Previous</a>
          </li>
          {%endif%}

          {%for n in totalpagelist %}
          <li class="page-item"><a class="page-link" href="/?page={{n}}">{{n}}</a></li>
         
          {%endfor%}
          {% if post.has_next %}	
          
          <li class="page-item">
          <a class="page-link" href="/?page={{post.next_page_number}}">Next</a>
          </li>
          <li class="page-item">
          <a class="page-link" href="/?page={{lastpage}}">Last</a>
          </li>
          {%endif%}
        </ul>
        </nav>
        

        </div>

      </div>
    </section><!-- End Team Section -->

    

  </main><!-- End #main -->

  {% endblock %}

templates/post_list.html
{% extends 'postbase.html' %}
{%load static%}
{% block body %}  

	
    <!-- ======= Why Us Section ======= -->
    <section id="why-us" class="why-us">
      <div class="container">

        
        <div class="row">
          {% if post|length < 1 %}
          <p style="background-color:green;font-size:large;color:white"><b>OOPS! There is No More Post</b></p>
          {% endif %}

          {% for i in post %}
          <div class="col-lg-4">
            <div class="box"  data-aos="fade-up " style="height: 550px;;" >
              <img src="{{i.image.url}}" style="height:200px;width:300px;" alt="">
              <a href="/userpost_details/{{i.slug}}"><h4>{{i.title|slice:"0:50"}}</h4></a>
              <p>{{i.desc|slice:"0:150"|safe}} </p>
             
              <p class="my-3">{{i.date}}</p>
              <a href="/edit_post2/{{i.id}}"><button class="btn btn-success">Edit</button></a>
              <a href="/delete_post/{{i.id}}"><button class="btn btn-danger">Delete</button></a>
            </div>
          </div>

          
          {% endfor %}



        </div>
          <!-- pagination -->
          <br><br>
    
       <nav aria-label="...">
        <ul class="pagination">
        {% if post.has_previous %}	
          <li class="page-item ">
          <a class="page-link" href="/post_list?page=1" tabindex="-1" aria-disabled="true">First</a>
          </li>
          <li class="page-item ">
          <a class="page-link" href="/post_list?page={{post.previous_page_number}}" tabindex="-1" aria-disabled="true">Previous</a>
          </li>
          {%endif%}

          {%for n in totalpagelist %}
          <li class="page-item"><a class="page-link" href="/post_list?page={{n}}">{{n}}</a></li>
         
          {%endfor%}
          {% if post.has_next %}	
          
          <li class="page-item">
          <a class="page-link" href="/post_list?page={{post.next_page_number}}">Next</a>
          </li>
          <li class="page-item">
          <a class="page-link" href="/post_list?page={{lastpage}}">Last</a>
          </li>
          {%endif%}
        </ul>
        </nav>

      </div>
    </section><!-- End Why Us Section -->

  </main><!-- End #main -->

   {% endblock %}

templates/userlogin.html
{% extends 'base.html' %}
{%load static%}
{% block body %}  

{%for msg in messages%}
<div class="alert alert-{{msg.tags}} alert-dismissible fade show" role="alert">
  <strong>Message : </strong> {{msg}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{%endfor%}
  <!-- ======= Contact Section ======= -->


  <section id="contact" class="contact">
    <div class="container">

      <div class="row mt-5">


        <div class="col-lg-11 mt-5 mt-lg-0" data-aos="fade-left">

          <form action="{% url 'userlogin' %}" method="post" enctype="multipart/form-data" role="form" >{% csrf_token %}
            <div class="row">
            <div class="form-group mt-3">
              <input type="text" class="form-control" name="username"  placeholder="USERNAME" required>
            </div>
            <div class="form-group mt-3 my-2">
              <input type="password" class="form-control" name="password"   placeholder="PASSWORD" required>
            </div>
            
            
            <div ><button type="submit" class="btn btn-success my-3">Login Here...</button></div>
          </form>

        </div>

        <div class="col-lg-11 mt-5 mt-lg-0" data-aos="fade-left">
          <a href="/usersignup">Registration here...</a>
        </div>
      </div>

    </div>
  </section><!-- End Contact Section -->

 {% endblock %}

templates/userpost_details.html
{% extends 'postbase.html' %}
{%load static%}
{% block body %}  
    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row gy-4">
          {% for i in post%}
          <div class="col-lg-6">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">
               
                <div>
                  <img src="{{i.image.url}}"   style="height: 400px; width: 600px;" alt="">
                </div>

              </div>
             
            </div>
          </div>
          {%endfor%}

          <div class="col-lg-6 ">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">
                
               
                <div   >
                  
                  <img src="{% static 'assets/img/testimonials-bg.jpg' %}"   style="height: 400px; width:600px;" alt="">
                </div>

              </div>
             
            </div>
          </div>
          
          {% for i in post%}
          <div class="col-lg-12">
           
            <div class="portfolio-description">
              <h2>{{i.title}}</h2>
              <p>
               {{i.desc|safe}}
              </p>
            </div>
          </div>
          {%endfor%}
        </div>

      </div>
    </section><!-- End Portfolio Details Section -->

  </main><!-- End #main -->

   {%endblock%}

templates/usersignup.html
{% extends 'base.html' %}
{%load static%}
{% block body %}  

{%for msg in messages%}
<div class="alert alert-{{msg.tags}} alert-dismissible fade show" role="alert">
  <strong>Message : </strong> {{msg}}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{%endfor%}
  <!-- ======= Contact Section ======= -->


  <section id="contact" class="contact">
    <div class="container">

      <div class="row mt-5">


        <div class="col-lg-11 mt-5 mt-lg-0" data-aos="fade-left">

          <form action="{% url 'usersignup' %}" method="post" enctype="multipart/form-data" role="form" >{% csrf_token %}
            <div class="row">
            <div class="form-group mt-3">
              <input type="text" class="form-control" name="username"  placeholder="Username" required>
            </div>
            <!-- <div class="form-group mt-3">
                <input type="email" class="form-control" name="email"  placeholder="Email" required>
              </div> -->
            <div class="form-group mt-3 my-2">
              <input type="password" class="form-control" name="pass1"   placeholder="Password" required>
            </div>
            <div class="form-group mt-3 my-2">
                <input type="password" class="form-control" name="pass2"   placeholder="Confirm Password" required>
              </div>
            
            <div ><button type="submit" class="btn btn-success my-3">Signup Here...</button></div>
            <div >
             <a href="{% url 'userlogin' %}">Login Here...</a> 
            </div>
          </form>

        </div>

       
      </div>

    </div>
  </section><!-- End Contact Section -->

 {% endblock %}